version: '3'
services:
   selenium-hub:
      #image: selenium/hub:3.141.59-20200515
      image: selenium/hub:4.0.0
      ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
      environment:
        GRID_MAX_SESSION: 5
        GRID_BROWSER_TIMEOUT: 300
        GRID_TIMEOUT: 300
   chrome:
      #image: selenium/node-chrome:3.141.59-20200515
      image: selenium/node-chrome:4.0.0
      depends_on:
         - selenium-hub
      shm_size: 2gb
      volumes:
         - /dev/shm:/dev/shm
      environment:
         SE_EVENT_BUS_HOST: selenium-hub
         SE_EVENT_BUS_PUBLISH_PORT: 4442
         SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
         SCREEN_WIDTH: 1920
         SCREEN_HEIGHT: 1080
         # set false for headless execution
         START_XVFB: "false"
         NODE_MAX_SESSION: 1
         NODE_MAX_INSTANCES: 1
